Feature/iii 3588 panel component
cultuurnet/udb3-frontend pull request #106
Opened 2020-11-03 13:24 UTC by simon-debruijn

### Added

- Panel component
- PanelFooter component
- Panel story

---

Ticket: https://jira.uitdatabank.be/browse/III-3588

2020-11-04 13:03 UTC, brampauwelyn requested changes

2020-11-04 13:03 UTC, brampauwelyn commented on src/components/publiq-ui/Panel.js
> +  border: 1px solid #ddd;
Maybe use a color variable here? From the theme.js file?

2020-11-04 13:03 UTC, brampauwelyn commented on src/components/publiq-ui/PanelFooter.js
> +  background-color: #f5f5f5;
use color variable

2020-11-05 15:44 UTC, geoffreydhuyvetters approved these changes

2020-11-05 16:08 UTC, merged