Feature/iii 3588 add introduction storybook
cultuurnet/udb3-frontend pull request #111
Opened 2020-11-04 13:36 UTC by simon-debruijn

### Added

- Design principles
- config to change the order of the stories

### Changed

- Text of Design principles

---

Ticket: https://jira.uitdatabank.be/browse/III-3588

2020-11-04 15:10 UTC, brampauwelyn requested changes

2020-11-04 15:10 UTC, brampauwelyn commented on src/components/publiq-ui/docs/DesignPrinciples.stories.mdx
> +We use [Styled Components](https://styled-components.com/) for the styling of our components wich makes them scoped by default.
*which

2020-11-04 15:10 UTC, brampauwelyn commented on src/components/publiq-ui/docs/DesignPrinciples.stories.mdx
> +Every Bootstrap component we use in React should be wrapped in a custom component inside Publiq UI.
inside the `publiq-ui` folder?

2020-11-04 15:10 UTC, brampauwelyn commented on src/components/publiq-ui/docs/DesignPrinciples.stories.mdx
> +Font sizes should be configured once globally and then not overridden in specific components.
This sentence is a bit weird.
Do you mean that you aren't allowed to override them in the components?

2020-11-05 08:51 UTC, brampauwelyn approved these changes

2020-11-05 13:46 UTC, geoffreydhuyvetters approved these changes

2020-11-05 14:48 UTC, merged