III-4922 - rounded corners
cultuurnet/udb3-frontend pull request #432
Opened 2022-10-07 14:10 UTC by simon-debruijn

### Added

-  Rounded corners

---

Ticket: https://jira.uitdatabank.be/browse/III-4922

2022-10-10 13:57 UTC, brampauwelyn commented
No rounded corners on the image & video upload box?

<img width="1159" alt="Screenshot 2022-10-10 at 15 56 01" src="https://user-images.githubusercontent.com/9402377/194882929-df706f67-f494-4eee-9bc8-c79e3149c3da.png">

+ not much contrast between background of box & the button

2022-10-11 07:35 UTC, brampauwelyn requested changes
Looks good! Love the rounded 🌽ers

2022-10-11 07:35 UTC, brampauwelyn commented on src/ui/DatePicker.tsx
> +          border-radius: 8px;
I wonder if we should put this border-radius value in some kind of global variable?
I see 8px is being used in a lot of places? 
Maybe nice if we want to change the value later?

2022-10-11 07:35 UTC, brampauwelyn commented on src/ui/Input.tsx
> +      css="border-radius: 8px;"
use global variable?

2022-10-11 07:35 UTC, brampauwelyn commented on src/ui/Modal/ContentModal.js
> +        border-radius: 8px;
use global variable?

2022-10-11 07:35 UTC, brampauwelyn commented on src/ui/Pagination.tsx
> +          */ &:hover {
Should this be part be in comment? 
Or can it be removed?

```suggestion
           &:hover {
```

2022-10-11 15:07 UTC, simon-debruijn commented
TODO:

Fix active state

![Screenshot 2022-10-11 at 17 07 07](https://user-images.githubusercontent.com/66943525/195128946-cc5944e7-1f3a-4abc-99cf-2df6fb75cfb3.png)

2022-10-12 08:36 UTC, simon-debruijn commented
@brampauwelyn 

![Screenshot 2022-10-12 at 10 31 15](https://user-images.githubusercontent.com/66943525/195293399-a3c25f7e-7096-4bbe-bb62-1fc02d91b1ee.png)

2022-10-12 11:10 UTC, brampauwelyn approved these changes

2022-10-12 12:38 UTC, merged